# .streamlit/secrets.toml

# SMTP for sending OTP emails
[smtp]
host = "smtp.gmail.com"
port = 587
username = "your-email@gmail.com"
password = "your-smtp-password-or-app-password"

# Google OAuth credentials (register at Google Cloud Console)
[google_oauth]
client_id = "YOUR_GOOGLE_CLIENT_ID"
client_secret = "YOUR_GOOGLE_CLIENT_SECRET"
redirect_uri = "http://localhost:8501/_oauth/google/callback"  # example for local

# App settings
[app]
admin_secret_code = "admin" 
default_admin_username = "admin"
default_admin_email = "admin@example.com"
default_admin_password = "ChangeThis123!"
